name: PR Checks

on:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Frontend Image
        run: |
          docker build -t frontend ./app/frontend

      - name: Build Backend Image
        run: |
          docker build -t backend ./app/backend

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .