name: PR Checks

on:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r app/backend/requirements.txt
          pip install pytest httpx

      - name: Run Unit Tests
        run: |
          pytest