name: PR Checks

on:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r app/backend/requirements.txt
          pip install pytest httpx

      - name: Run Unit Tests
        run: |
          pytest

      ###################################################
      # Dependency Scan
      ###################################################

      - name: Install pip-audit
        run: |
          pip install pip-audit

      - name: Dependency Vulnerability Scan
        run: |
          pip-audit -r app/backend/requirements.txt

      ###################################################
      # Container Scan
      ###################################################

      - name: Build Backend Image
        run: |
          docker build -t backend-test ./app/backend

      - name: Scan Backend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: backend-test
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH